{
    "name": "Real Estate Management",
    "auther": "Mahmoud Gaber",
    "description": "Manage Real Estate Properties",
    "category": "Business",
    "version": "17.0.0.1.0",
    "depends": ['base', 'sale_management', 'mail', 'contacts', 'account_accountant'],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/base_menu.xml',
        'views/property_view.xml',
        'views/owner_view.xml',
        'views/sale_order_view.xml',
        'views/client_view.xml',
        'views/res_partner_view.xml',
        'views/building_view.xml',
        'views/property_history_view.xml',
        'views/account_move_view.xml',
        'wizard/change_state_wizard_view.xml',
        'reports/property_report.xml',
    ],
    "assets": {
        'web.assets_backend': ['real_estate/static/src/css/property.css'],
        'web.report_assets_common': ['real_estate/static/src/css/font.css']
    },
    "installable": True,
    "application": True,
}
